--

diff --git a/bin/zwikirepo b/bin/zwikirepo
--- a/bin/zwikirepo
+++ b/bin/zwikirepo
@@ -1,261 +1,259 @@
 #!/bin/bash
-#
-# by borzole.one.pl
-# VERSION = 2010.02.02 22:34
+
+# zwikirepo -- pobiera paczki RPM prosto z http://wiki.fedora.pl/wiki/repo
+# 				wersja GUI (zenity)
+# autor: borzole (jedral.one.pl)
+# licencja: GPLv2+
 # ------------------------------------------------------------------------------
-# zwikirepo - pobiera paczki RPM prosto z http://wiki.fedora.pl/wiki/repo
-# wersja GUI (zenity)
-# 
-# Zmiany GUI:
-# 2009.12.19
-#	- zmiana, pasek postępu w funkcji main używa osobnego deskryptora pliku
-#	dzięki temu jest przejrzyściej i izolowany jest pasek, a nie kod.
-#	- zmiana, powiadomienia o aktualizacji ma teraz ikonkę
-# 2009.12.16
-#	- zmiana paska startowego na pulsujący
-# 2009.12.14
-#	- mniej nachalne potwierdzenie aktualizacji
-#	- dodałem "zenity --progress" na stacie skryptu
-#	- autoupdate w tle
-#	- zmiany w nazewnictwie kilku funkcji
-#	- inne drobne korekty
-# 2009.12.06
-#	- usunąłem $TERM na rzecz xterm (parametr jest ustawiony tylko jeśli program startuje z konsoli)
+VERSION=2010.02.28-17:50
+# Zmiany: użyj "meld" lub "diff" to się dowiesz ;P
 # ------------------------------------------------------------------------------
-# Zmiany SILNIK:
-# 2010.02.02
-#	- poprawka, link typu "https" rozwalał listę
-# 2009.12.16
-#	- poprawka, skrypt nie usuwał śmieci w tmp po sprawdzaniu aktualizacji
-# 2009.12.14
-#	- przebudowa skryptów pod moje "bside", z tego powodu pewne parametry mogą być zbędne
-#	- dodane sprawdzenie aktualizacji
-# 2009.12.13
-#	- poprawka, niedostateczne filtrowanie linków, dodałem grep 'http'
-# 2009.12.02
-#	- poprawka, źle grep filtrował linki
-#	- dodanie funkcji "wymaga" do sprawdzenia wymaganych zależności
-# 2009.11.27
-#	- poprawka wyboru katalogu
-# 	- ładowanie listy w locie do tablicy zamiast plików
-# 	- jeden silnik, dwa interfejs: CLI i ZENITY
-# 	- porzucenie instalacji paczek z poziomu skryptu (nie działało :( )
-# 2009.11.24
-# 	- poprawka sortowania listy paczek
+# domyślny folder pobierania
+DIR=$HOME
+# ------------------------------------------------------------------------------
+# tytuł okien
+TITLE="${0##*/} ver.$VERSION"
 # ------------------------------------------------------------------------------
 export DISPLAY=:0.0
 export LANG=pl_PL.UTF-8
 export PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
 # ------------------------------------------------------------------------------
-BASE="$0"
-BASENAME="${0##*/}"
-# na potrzeby wewnętrznych funkcji
-ARGS="${@}"
-VERBOSE=TRUE
-DEBUG=FALSE
-VERSION_LOCAL=$(grep -E '^#\ *VERSION\ *='  ${0} | cut -d\= -f2)
+usage(){
+	echo -e "  ${0##*/} -- pobiera paczki RPM prosto z http://wiki.fedora.pl/wiki/repo
 
+Użycie:
+  ${0##*/} [OPCJA...]
+
+Opcje:
+  -l, --list                   Wyświetl listę linków bez GUI i zakończ program
+                               (umożliwia własne przetwarzanie tych danych)
+  -V, --version                Wyświetl informacje o wersji i zakończ program
+  -h, --help                   Wyświetla opcje pomocy
+
+Autor:
+  borzole (jedral.one.pl)
+
+Licencja:
+  GPLv2+
+"
+}
 # ------------------------------------------------------------------------------
-# czcionka: (N)ORMAL, (X)BOLD, (R)ED, (G)REEN, (B)LUE
-N="\e[0m" 
-X="\e[1;38m" 
-r="\e[0;31m"
-R="\e[1;31m"
-g="\e[0;32m"
-G="\e[1;32m"
-b="\e[0;34m"
-B="\e[1;34m"
-# ------------------------------------------------------------------------------
-# domyślny folder pobierania
-DIR=$HOME
+usage_gui(){
+	# wyświetla pomoc w wersji okienkowej
+	usage | zenity --title="$TITLE" --text-info --width=500 --height=350 
+	menu_function
+}
 # ------------------------------------------------------------------------------
 get_links(){
-	# zwraca listę linków do paczek rpm oddzielona znakiem nowego wiersza
+	# zwraca listę linków do paczek rpm oddzieloną znakiem nowego wiersza
 	# informacja jest wyłuskiwana z tej strony
-	URL="http://wiki.fedora.pl/index.php?title=repo&action=raw&ctype=text/css"	
-	# metoda: 
-	#		- sed: każdą spację zamienić na znak nowej linii ( składnia linków na wiki wymusza tę spację)
-	#		- grep: wylapać tylko linie kończące się na ".rpm"
-	#		- awk: wyłuskać linie zawierające linki i wyłuskać link http
-	#		- sort: posortowanie i usunięcie pustych linii
-	
-	# http://
-	# https://
-	# ftp://
-	curl -s ${URL}  \
-		| sed -e 's/\ \ */\n/g' \
-		| grep '[ftphs]*\:\/\/.*\.rpm$' \
-		| awk -F "://" '{ print $2 }' \
+	local thisURL="http://wiki.fedora.pl/index.php?title=repo&action=raw&ctype=text/css"
+	# metoda:
+	#	- sed: każdą "spację" i "[" zamienić na znak nowej linii
+	#		( składnia linków na wiki wymusza tę spację i nawias )
+	#	- grep: wylapać tylko linie zaczynające się od:
+	#			http://
+	#			https://
+	#			ftp://
+	#			i kończące się na ".rpm"
+	#	- sort: posortowanie i usunięcie pustych linii	
+	curl -s "$thisURL"  \
+		| sed -e 's/\ \ */\n/g ; s/\[/\n/g' \
+		| grep -E '^(http|https|ftp)\:\/\/.*\.rpm$' \
 		| sort -u 
 }
 # ------------------------------------------------------------------------------
 set_rpmlist(){
+	# inicjalizuje listę paczek z repo
+	# deskryptor pliku 4 = wejście informacyjne dla paska postępu
+	exec 4> >(zenity --progress --pulsate --width=300 --auto-close --auto-kill --title="$TITLE")
+	echo "# Pobieram listę paczek ..." >&4
 	# załaduj listę linków do jednej tabeli
 	unset RPMLIST
-	RPMLIST=( $(get_links))
-}
-# ------------------------------------------------------------------------------
-wymaga(){
-	# sprawdza zależności skryptu 
-	# np.
-	# 		wymaga wget zenity notify-send
-	for apps in "$@" ; do
-		which ${apps} >/dev/null 2>&1
-		if [ $? != 0 ] ; then
-			echo -e "${R}[ ERROR ] Nie znaleziono programu \"$apps\""
-			echo -e "${G}Spróbuj zainstalować:"
-			echo -e "\tsu -c'yum install $apps'"
-			echo -e "a jeśli zawiedzie, to spróbuj odnaleźć paczkę dostarczającą wymaganą zależność:"
-			echo -e "\tsu -c'yum provides \\*bin/$apps'"
-			exit 1;
-		fi
-	done
-}
-# ------------------------------------------------------------------------------
-UPDATE_URL="http://dl.dropbox.com/u/409786/pub/bin/zwikirepo"
-# ------------------------------------------------------------------------------
-main(){
-	wymaga wget curl xterm zenity
-	
-	# deskryptor pliku 4 = wejście informacyjne dla paska postępu
-	exec 4> >(zenity --progress --pulsate --width=300 --auto-close --auto-kill  --title="$BASENAME ver.$VERSION_LOCAL" )
-	echo "# Pobieram listę paczek ..." >&4
-	set_rpmlist 
+	RPMLIST=($(get_links))
 	# wysłanie setki wywoła "--auto-close" i pasek zniknie
 	echo "100" >&4
 	# zamknięcie deskryptora 4
 	exec 4>&-
-	check_script_update &	
-	ui 
 }
 # ------------------------------------------------------------------------------
-ui(){
-	show_menu_rpmlist
+init(){
+	while [ $# != 0 ] ; do
+		case "$1" in
+			-l|--list)
+				# pokaż listę rpm i wyjdź
+				get_links
+				exit 0
+				;;
+			-V|--version)
+				echo $VERSION
+				exit 0
+				;;
+			-h|--help)
+				usage
+				exit 0
+				;;
+			*)
+				usage
+				exit 1
+				;;
+		esac
+	done
 }
 # ------------------------------------------------------------------------------
-check_script_update(){
+requires(){
+	# sprawdza zależności skryptu
+	local thisSTATUS=OK
+	# czcionka: (N)ORMAL, (R)ED
+	local N="\e[0m" 
+	local R="\e[1;31m"
+
+	for APPS in "$@" ; do
+		type ${APPS} >/dev/null 2>&1
+		if [ $? != 0 ] ; then
+			echo -e "${R}[ ERROR ]${N} Nie znaleziono programu '${R}$APPS${N}'" >&2
+			thisSTATUS=ERROR
+		fi
+	done
+	
+	# podsumowanie testu
+	if [ $thisSTATUS == 'ERROR' ] ; then
+		echo -e "a) zainstaluj program:
+			\r\tsu -c'yum install aplikacja'
+			\rb) lub odszukaj paczkę dostarczającą wymaganą zależność:
+			\r\tsu -c'yum provides aplikacja'
+			\r\tsu -c'yum provides \\*bin/aplikacja'" >&2
+		exit 1;
+	fi
+}
+# ------------------------------------------------------------------------------
+main(){
+	# główna
+	init $@
+	requires wget curl xterm zenity notify-send
+	set_rpmlist
+	update &
+	ui
+}
+# ------------------------------------------------------------------------------
+update(){
+	# sprawdzanie aktualizacji
+	local thisUPDATE_URL="http://dl.dropbox.com/u/409786/pub/bin/zwikirepo"
 	UPDATE_FILE=$(mktemp)
-	trap "rm -f $UPDATE_FILE 2>/dev/null" EXIT
-	curl -s "$UPDATE_URL"  > $UPDATE_FILE
 	# jeśli coś przerwie skrypt to usuń ten plik
-	
-	VERSION_LAST=$(grep -E '^#\ *VERSION\ *='  $UPDATE_FILE | cut -d\= -f2)
-	
-	[ "$VERSION_LOCAL" != "$VERSION_LAST" ] && show_script_update
+	trap "rm -f $UPDATE_FILE 2>/dev/null" EXIT
+	curl -s "$thisUPDATE_URL"  > $UPDATE_FILE
+	VERSION_LAST=$(grep -E '^VERSION=' $UPDATE_FILE | cut -d\= -f2)
+	[ "$VERSION" != "$VERSION_LAST" ] && update_script
 	exit 0 
 }
 # ------------------------------------------------------------------------------
-save_update_file(){
-	SAVE_UPDATE_FILE=$(zenity --file-selection --title="Zapisz aktualną wersję jako ...")
+update_save_file(){
+	UPDATE_FILE_SAVE=$(zenity --title="Zapisz aktualną wersję jako ..." \
+					--file-selection \
+					--filename=${0##*/} \
+					--save --confirm-overwrite )
 	if [ $? != 0 ] ; then
 		# w razie nie wybrania niczego
-		zenity --question --title="$BASENAME ver.$VERSION_LOCAL" \
+		zenity --question --title="$TITLE" \
 				--text "Nie wybrano gdzie zapisać aktualną wersję !\n Chcesz spróbować zapisać jeszcze raz?"
-		[ $? == 0 ] && save_update_file
+		[ $? == 0 ] && ${FUNCNAME}
 	fi
 }
 # ------------------------------------------------------------------------------
-show_script_update(){
-	
+update_script(){
+	local thisINFO="Dostępna jest aktualizacja skryptu"
+	local thisINFO_LONG="<i>$thisINFO: <big><span color='red'>${0##*/}</span>!</big></i>"
+
 	# dymek
-	echo "message:<i>Dostępna jest aktualizacja skryptu:</i> \\n<span color='red'>zwikirepo</span>!" | zenity --notification --listen
+	notify-send --urgency critical --expire-time 4000 "$TITLE" "$thisINFO_LONG"
 	# ikona
-	zenity --notification --text "Dostępna jest aktualizacja skryptu !"
+	zenity --notification --text "$thisINFO '${0##*/}'!"
 	# kliknięcie na ikonę
 	if [ $? == 0 ] ; then
-		zenity --question --title="$BASENAME ver.$VERSION_LOCAL" \
-				--text "Dostępna jest aktualizacja skryptu !\n
-$VERSION_LOCAL - lokalna wersja
-<b>$VERSION_LAST</b> - ostatnia wersja
-		
-...możesz ją od razu zapisać"
-		[ $? == 0 ] && save_update_file
-		[ $? == 0 ] && mv $UPDATE_FILE "$SAVE_UPDATE_FILE"
+		zenity --question --title="$TITLE" --width=400 \
+			--text "$thisINFO_LONG
+			\r$VERSION - lokalna wersja	\n<b>$VERSION_LAST</b> - ostatnia wersja
+			\rZapisać ostatnią wersję?"
+		[ $? == 0 ] && update_save_file
+		[ $? == 0 ] && mv $UPDATE_FILE "$UPDATE_FILE_SAVE"
 		
 	fi
+}
+# ------------------------------------------------------------------------------
+ui(){
+	menu_rpmlist
 }
 # ------------------------------------------------------------------------------
 set_dir(){
-	TMP="$DIR"
-	DIR=$(zenity --file-selection --directory --title="Wybierz katalog")
-	if [ $? != 0 ] ; then
-		# w razie nie wybrania niczego
-		DIR="$TMP"
-	fi
-	show_menu_function
+	# ustawienie folderu pobierania
+	TMP=$(zenity --file-selection --directory --title="Wybierz katalog")
+	[ $? == 0 ] && DIR="$TMP"
+	menu_function
 }
 # ------------------------------------------------------------------------------
 download(){			
-		mkdir -p "$DIR" 2>/dev/null
-		for RPMNR in ${LISTA} ; do
-			xterm -e wget -P "$DIR" "$1" "${RPMLIST[${RPMNR}]}"
-		done		
+	[ ! -d "$DIR" ] && mkdir -p "$DIR"
+	for RPMNR in ${LISTA} ; do
+		# usunąłem $TERM na rzecz xterm
+		# bo parametr jest ustawiony tylko jeśli program startuje z konsoli
+		xterm -e wget -P "$DIR" "$1" "${RPMLIST[${RPMNR}]}"
+	done		
 }
 # ------------------------------------------------------------------------------
-show_menu_function(){
-	# Menu główne poleceń
-	menu_function(){
-		zenity --title="$BASENAME ver.$VERSION_LOCAL"  --text "::TODO::" \
-				--list  --radiolist --width=400 --height=200 \
-				--column="radiolist" --column "wybierz" --column "polecenie do wykonania" \
-					TRUE		"Pobierz pakiet(y)"								"download"\
-					FALSE		"Pobierz pakiet(y) w drzewo :)" 			"download -x"\
-					FALSE		"Zmień folder pobierania: $DIR"			"set_dir"\
-				--print-column=3 --hide-column=3
-		}
-	# wykonanie poleceń
-	$(menu_function)
+menu_function_show(){
+	# okno z listą funkcji
+	zenity 	--title="$TITLE"  --text "Drobne ustawienia i hopa :)" \
+		--list  --radiolist --width=400 --height=200 \
+		--column="todo" --column "polecenie do wykonania" --column "" \
+			TRUE	"Pobierz pakiet(y)"					"download"\
+			FALSE	"Pobierz pakiet(y) w drzewo :)" 	"download -x"\
+			FALSE	"Zmień folder pobierania: $DIR"		"set_dir"\
+			FALSE	"Pomoc"								"usage_gui"\
+		--print-column=3 --hide-column=3
+}
+# ------------------------------------------------------------------------------
+menu_function(){
+	# obsługa menu poleceń
+	# wykonanie poleceń:
+	$(menu_function_show)
 	# powrót do głównego menu
-	show_menu_rpmlist
+	menu_rpmlist
 }
 # ------------------------------------------------------------------------------
-menu_rpmlist_format(){
-		for ((i = 0; i < ${#RPMLIST[@]} ; i++)); do
-			RPMNR=i
-			echo -e " FALSE ${RPMLIST[$i]##*/} $i ${RPMLIST[$i]}"
-		done
+menu_rpmlist_table(){
+	# tabela wypełniające menu paczek
+	for ((i = 0; i < ${#RPMLIST[@]} ; i++)); do
+		echo -e " FALSE ${RPMLIST[$i]##*/} $i ${RPMLIST[$i]}"
+	done
 }
 # ------------------------------------------------------------------------------
-show_menu_rpmlist(){
-	menu_rpmlist() {
-		RPMCOUNT=${#RPMLIST[@]}
-		let "$RPMCOUNT++"
-		zenity --title="$BASENAME ver.$VERSION_LOCAL" \
-			--text "Paczki pochodzą wprost ze strony:\t<b>http://wiki.fedora.pl/wiki/repo</b> \nZnaeziono <b>$RPMCOUNT</b> pakiety. Wybierz pakiety do pobrania:" \
-			--width=1024 --height=800 \
-			--list  --checklist \
-			--column="zaznacz" --column "paczka" --column "nr" --column "url" \
-			$(menu_rpmlist_format|sort) \
-			--separator " "  --multiple \
-			--print-column=3 --hide-column=3
-	}	
-	LISTA=$(menu_rpmlist)
+menu_rpmlist_show() {
+	# okno z listą paczek
+	zenity --title="$TITLE" \
+		--text "Paczki pochodzą wprost ze strony:\t<b>http://wiki.fedora.pl/wiki/repo</b>\nZnaleziono <b>${#RPMLIST[@]}</b> pakiety. Wybierz pakiety do pobrania:" \
+		--width=1024 --height=800 \
+		--list  --checklist \
+		--column="zaznacz" --column "paczka" --column "nr" --column "url" \
+		$(menu_rpmlist_table|sort) \
+		--separator " "  --multiple \
+		--print-column=3 --hide-column=3
+}
+# ------------------------------------------------------------------------------
+menu_rpmlist(){
+	# obsługa menu z paczkami
+	LISTA=$(menu_rpmlist_show)
 	if [ $? != 0 ] ; then
 		exit 0
 	elif [ ${#LISTA} == 0 ] ; then
-			# ------------------------------------------------------------------------------
-			zenity --question --title="$BASENAME ver.$VERSION_LOCAL" \
-					--text "Nic nie zaznaczono !?" \
-					--ok-label="OK : już coś wybieram " \
-					--cancel-label="Quit : bye bye :)" \
-			# ------------------------------------------------------------------------------
-			if [ $? != 0 ] ; then
-				exit 0;
-			else
-				# powrót do głównego menu
-				show_menu_rpmlist
-			fi
+		zenity --question --title="$TITLE" \
+			--text "Nie zaznaczono żadnych pakietów!" \
+			--ok-label="Lista" \
+			--cancel-label="Exit"
+		[ $? == 0 ] && ${FUNCNAME}
 	else
-		show_menu_function
+		menu_function
 	fi
 }
 # ------------------------------------------------------------------------------
-# uruchomienie funkcji głównej lub z parametru
-if [ -n "$1" ] ; then 
-	"${ARGS}"
-else 
-	main
-fi
-# wyjście z przekazaniem kodu wyjścia ostatniego polecenia
-exit $?
-# ------------------------------------------------------------------------------
+main $@
